import type { Company } from "./types";

export const companies: Company[] = [
  {
    id: 1,
    name: "UzMarket LLC",
    slug: "uzmarket",
    phone: "+998901234567",
    email: "info@uzmarket.uz",
    website: "https://uzmarket.uz",
    address: "Tashkent, Amir Temur street 12",
    logo: "https://via.placeholder.com/120x60.png?text=UzMarket",
    createdAt: "2023-04-15T10:30:00.000Z",
    isActive: true,
    employees: 48,
    revenueUSD: 420000,
    categories: ["E-commerce", "Retail"],
    description: "Leading online marketplace in Uzbekistan for electronics and home goods.",
  },
  {
    id: 2,
    name: "AgroDrip Solutions",
    slug: "agrodrip",
    phone: "+998937001122",
    email: "contact@agrodrip.uz",
    website: "https://agrodrip.uz",
    address: "Fergana region, Agropark 3",
    logo: "https://via.placeholder.com/120x60.png?text=AgroDrip",
    createdAt: "2021-09-01T08:15:00.000Z",
    isActive: true,
    employees: 12,
    revenueUSD: 85000,
    categories: ["Agriculture", "IOT"],
    description: "Smart drip irrigation hardware and monitoring for small farms.",
  },
  {
    id: 3,
    name: "Studio PixelArt",
    slug: "pixelart",
    phone: "+998712223344",
    email: "hello@pixelart.design",
    website: "https://pixelart.design",
    address: "Samarkand, Creative hub, Bldg 7",
    logo: "https://via.placeholder.com/120x60.png?text=PixelArt",
    createdAt: "2020-02-20T14:00:00.000Z",
    isActive: false,
    employees: 6,
    revenueUSD: 25000,
    categories: ["Design", "Agency"],
    description: "Small design studio focused on UI/UX and brand identity.",
  },
];